services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
      target: development
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - interna

  nginx:
    image: nginx
    ports:
      - "80:8013"
    volumes:
      - ./:/var/www/html/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - interna

networks:
  interna: 
   driver: bridge
